import * as arrow from "apache-arrow";
import { csvParseRows } from "d3-dsv";
import { DataSource, SqlColumnType } from "./datasource";
import { DataSchema } from "./types";
import { schemaToSqlType } from "./sql-pivot-datamodel";
import { GridError, GridErrorCode } from "../errors";

export type ColumnMetadata = DataSchema & {
  normColName: string;
  originalColName: string;
};

const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}(T|\s)/;

function sampleNonEmpty(columnValues: unknown[], maxSamples: number): unknown[] {
  const result: unknown[] = [];
  for (const v of columnValues) {
    if (v === null || v === undefined || v === "") continue;
    result.push(v);
    if (result.length >= maxSamples) break;
  }
  return result;
}

function isISODateString(val: string): boolean {
  return ISO_DATE_RE.test(val) && !isNaN(Date.parse(val));
}

function inferColumnType(values: unknown[]): SqlColumnType {
  const samples = sampleNonEmpty(values, 20);
  if (samples.length === 0) return "VARCHAR";

  const allNumbers = samples.every((v) => typeof v === "number");
  if (allNumbers) {
    const hasDecimal = samples.some((v) => !Number.isInteger(v as number));
    return hasDecimal ? "DOUBLE" : "INTEGER";
  }

  const allNumericStrings = samples.every(
    (v) => typeof v === "string" && v !== "" && !isNaN(Number(v)),
  );
  if (allNumericStrings) {
    const hasDecimal = samples.some((v) => !Number.isInteger(Number(v)));
    return hasDecimal ? "DOUBLE" : "INTEGER";
  }

  const allDates = samples.every(
    (v) => typeof v === "string" && isISODateString(v),
  );
  if (allDates) return "TIMESTAMP";

  return "VARCHAR";
}

let tableCounter = 0;
function generateTableName(): string {
  return `__ds__${tableCounter++}`;
}

function buildCreateTableDDL(table: string, columns: Map<string, SqlColumnType>): string {
  const colDefs: string[] = [];
  for (const [name, type] of columns) {
    colDefs.push(`"${name}" ${type}`);
  }
  return `CREATE TABLE "${table}" (${colDefs.join(", ")})`;
}

/**
 * Abstract base class for SQL-backed data sources.
 *
 * Narrows `DataSource<T>` to `DataSource<string>` - the command to execute is always a SQL string.
 * On top of query execution, it provides data ingestion via `loadData()` and `loadDataFromURL()`.
 * Data must be provided in column-major format and is batched into the underlying SQL engine using Apache Arrow for efficient bulk inserts.
 *
 * Subclasses must implement `execute()`, `insertArrowTable()`, and `release()`.
 */
export abstract class SqlDataSource implements DataSource<string> {
  /**
   * The SQL table name where loaded data is stored. Auto-generated by `loadData()` if not provided.
   */
  table!: string;

  /** @internal */
  protected refCount = 1;

  /**
   * **Abstract.** Execute a SQL string against the underlying WASM-based SQL engine and return the result rows.
   * Implemented by concrete subclasses like `DuckDBWasmDataSource`.
   *
   * @param sql - A SQL query string (e.g. `"SELECT city, SUM(revenue) FROM sales GROUP BY city"`).
   * @returns Result rows as key-value records.
   */
  abstract execute(sql: string): Promise<Record<string, any>[]>;

  /**
   * Load column-major data from JS memory into the WASM-based SQL engine in the browser.
   *
   * Creates a table, inserts data using Apache Arrow, then casts each column
   * to its target type based on the provided schema.
   *
   * `data` is column-major: `data[i]` is the array of values for `schema[i]`.
   *
   * ```
   * schema: [{ name: "city" }, { name: "revenue" }]
   * data:   [["NYC", "LA"],     [100, 200]]
   *            ^ data[0]          ^ data[1]
   * ```
   *
   * @param config.schema - Array of [`DataSchema`](/docs/api-references/type-references#dataschema) column definitions describing name, type, and subtype.
   * @param config.data - Column-major array of values. `data[i]` corresponds to `schema[i]`, where each item in `data[i]` is a value of that column.
   * @param config.table - Optional table name. Auto-generated if omitted.
   * @param config.replace - Optional per-column string replacements applied before type casting. A `Map<columnName, Map<searchString, replaceString>>` - for each column, every occurrence of `searchString` in the cell value is replaced with `replaceString`. Useful for cleaning formatting like currency symbols or thousand separators (e.g. `"$1,000"` → `"1000"`).
   */
  async loadData(config: {
    table?: string;
    schema: DataSchema[];
    data: any[][];
    replace?: Map<string, Map<string, string>>;
  }): Promise<void> {
    this.table = config.table ?? generateTableName();

    const varcharColumns = new Map<string, SqlColumnType>(
      config.schema.map(s => [s.name, "VARCHAR"])
    );
    const ddl = buildCreateTableDDL(this.table, varcharColumns);
    await this.execute(ddl);

    const numRows = config.data[0]?.length ?? 0;
    if (numRows === 0) return;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const columns: Record<string, any> = {};
    for (let i = 0; i < config.schema.length; i++) {
      const colData = config.data[i];
      columns[config.schema[i].name] = colData.map((v: unknown) =>
        v === null || v === undefined ? null : String(v)
      );
    }

    const arrowTable = arrow.tableFromArrays(columns);
    await this.insertArrowTable(arrowTable, this.table);

    for (const s of config.schema) {
      const colReplacements = config.replace?.get(s.name);
      const targetType = schemaToSqlType(s);

      let expr = `"${s.name}"`;
      if (colReplacements) {
        for (const [search, rep] of colReplacements) {
          expr = `REPLACE(${expr}, '${search}', '${rep}')`;
        }
      }
      if (s.subtype === "temporal" && s.datetimeFormat) {
        expr = `strptime(${expr}, '${s.datetimeFormat}')`;
      }

      await this.execute(
        `ALTER TABLE "${this.table}" ALTER COLUMN "${s.name}" SET DATA TYPE ${targetType} USING ${expr}`
      );
    }
  }

  /**
   * Fetch data from a URL, parse it as JSON or CSV, infer the schema if not
   * provided, and load it into the SQL engine via `loadData()`.
   *
   * @param config.url - URL to fetch data from. A GET request is made using the browser's `fetch` API.
   * @param config.type - Format of the data: `"json"` (array of objects) or `"csv"`.
   * @param config.preprocess - Optional callback to transform the raw parsed data before loading.
   * @param config.schema - Optional column definitions. If omitted, types are inferred from values.
   * @param config.replace - Optional per-column string replacements applied before type casting. A `Map<columnName, Map<searchString, replaceString>>` - for each column, every occurrence of `searchString` in the cell value is replaced with `replaceString`. Useful for cleaning formatting like currency symbols or thousand separators (e.g. `"$1,000"` → `"1000"`).
   * @param config.table - Optional table name. Auto-generated if omitted.
   * @returns Column metadata with inferred or provided schema information.
   *
   * @throws `GridError` with the following codes:
   *
   * | Code | Name | When |
   * | --- | --- | --- |
   * | 1000 | `FETCH_FAILED` | Network error or non-2xx HTTP response |
   * | 1001 | `PARSE_FAILED` | JSON or CSV parsing fails |
   * | 1002 | `EMPTY_DATA` | Parsed result is an empty array |
   * | 1003 | `INVALID_DATA` | Parsed JSON is not an array of objects |
   */
  async loadDataFromURL(config: {
    url: string;
    type: "json" | "csv";
    preprocess?: (data: unknown) => unknown;
    schema?: DataSchema[];
    replace?: Map<string, Map<string, string>>;
    table?: string;
  }): Promise<ColumnMetadata[]> {
    let response: Response;
    try {
      response = await fetch(config.url);
    } catch (e) {
      throw new GridError(GridErrorCode.FETCH_FAILED, "Failed to fetch URL", e as Error, {
        url: config.url,
      });
    }
    if (!response.ok) {
      throw new GridError(GridErrorCode.FETCH_FAILED, "Failed to fetch URL", undefined, {
        url: config.url,
        status: response.status,
      });
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let parsed: any;
    let csvHeaders: string[] | undefined;
    let csvRows: string[][] | undefined;
    try {
      if (config.type === "json") {
        parsed = await response.json();
      } else {
        const text = await response.text();
        const rows = csvParseRows(text);
        csvHeaders = rows[0];
        csvRows = rows.slice(1);
      }
    } catch (e) {
      throw new GridError(GridErrorCode.PARSE_FAILED, "Failed to parse response", e as Error, {
        url: config.url,
      });
    }

    if (config.type === "json") {
      if (config.preprocess) {
        const preprocessed = config.preprocess(parsed);
        parsed = preprocessed ? preprocessed : parsed;
      }

      if (!Array.isArray(parsed) || parsed.length === 0) {
        if (Array.isArray(parsed)) {
          throw new GridError(GridErrorCode.EMPTY_DATA, "Parsed data is empty");
        }
        throw new GridError(GridErrorCode.INVALID_DATA, "Parsed data is not an array of objects");
      }
    } else {
      if (config.preprocess) {
        const preprocessed = config.preprocess(csvRows) as string[][];
        csvRows = preprocessed ? preprocessed : csvRows;
      }

      if (!csvRows || csvRows.length === 0) {
        throw new GridError(GridErrorCode.EMPTY_DATA, "Parsed data is empty");
      }
    }

    let columnOrder: string[];
    const inferredTypes = new Map<string, SqlColumnType>();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data: any[][] = [];

    if (config.type === "csv") {
      columnOrder = csvHeaders!;
      const colIndexMap = new Map<string, number>();
      for (let i = 0; i < csvHeaders!.length; i++) {
        colIndexMap.set(csvHeaders![i], i);
      }

      if (config.schema) {
        columnOrder = config.schema.map(s => s.name);
      }

      for (const col of columnOrder) {
        const ci = colIndexMap.get(col)!;
        const values = csvRows!.map((row) => row[ci]);
        inferredTypes.set(col, inferColumnType(values));
      }

      for (const col of columnOrder) {
        const ci = colIndexMap.get(col)!;
        const colValues = csvRows!.map((row) => {
          const v = row[ci];
          if (v === null || v === undefined || v === "") return null;
          return v;
        });
        data.push(colValues);
      }
    } else {
      columnOrder = config.schema ? config.schema.map(s => s.name) : Object.keys(parsed[0]);

      for (const col of columnOrder) {
        const values = parsed.map((row: Record<string, unknown>) => row[col]);
        inferredTypes.set(col, inferColumnType(values));
      }


      for (const col of columnOrder) {
        const colValues = parsed.map((row: Record<string, unknown>) => {
          const v = row[col];
          if (v === null || v === undefined || v === "") return null;
          return v;
        });
        data.push(colValues);
      }
    }

    const schema: DataSchema[] = config.schema
      ? config.schema.map(s => {
        if (s.type === "measure" && !s.subtype) {
          const inferred = inferredTypes.get(s.name);
          return { ...s, subtype: (inferred === "INTEGER" ? "integer" : "decimal") as DataSchema["subtype"] };
        }
        return s;
      })
      : columnOrder.map(col => {
        const inferred = inferredTypes.get(col)!;
        if (inferred === "INTEGER" || inferred === "DOUBLE") {
          return {
            name: col,
            type: "measure" as const,
            subtype: (inferred === "INTEGER" ? "integer" : "decimal") as DataSchema["subtype"],
          };
        }
        if (inferred === "TIMESTAMP") {
          return { name: col, type: "dimension" as const, subtype: "temporal" as const };
        }
        return { name: col, type: "dimension" as const };
      });

    // TODO: this should only be there in dev mode
    console.log("Schema inference:", schema);

    await this.loadData({ table: config.table, schema, data, replace: config.replace });

    const result: ColumnMetadata[] = [];
    for (const s of schema) {
      result.push({ ...s, normColName: s.name, originalColName: s.name });
    }
    return result;
  }

  /**
   * **Abstract.** Batch-insert an Apache Arrow table into the WASM-based SQL engine in the browser.
   * Called internally by `loadData()` after converting column-major arrays into an Arrow table.
   *
   * Row-by-row inserts into a WASM SQL engine are slow due to per-row overhead across the
   * JS-to-WASM boundary. Arrow's columnar memory layout allows the entire dataset to be
   * transferred in a single operation, making bulk loads significantly faster.
   *
   * Concrete subclasses must implement this to bridge Arrow data into their specific SQL engine.
   * The target table is already created before this method is called - the implementation only
   * needs to insert the data, not create the table.
   *
   * @param table - An Apache Arrow `Table` containing the data to insert.
   * @param name - The name of the existing SQL table to insert into.
   */
  protected abstract insertArrowTable(table: arrow.Table, name: string): Promise<void>;

  addRef(): void {
    this.refCount++;
  }

  /**
   * **Abstract.** Decrement the reference count and release underlying resources (connections, WASM instances) when the count reaches zero.
   */
  abstract release(): Promise<void>;
}
